apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ga-entry-hpa
spec:
  scaleTargetRef:
    apiversion: apps/v1
    kind: Deployment
    name: ga-entry
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40