apiVersion: apps/v1
kind: Deployment
metadata:
  name: ga-results
  labels:
    app: ga-results
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ga-results
  template:
    metadata:
      labels:
        app: ga-results
    spec:
      containers:
      - name: results
        image: manrajbhullar/ga_results
        ports:
        - containerPort: 8090
        resources:
          requests:
            cpu: 100m