apiVersion: apps/v1
kind: Deployment
metadata:
  name: ga-analytics
  labels:
    app: ga-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ga-analytics
  template:
    metadata:
      labels:
        app: ga-analytics
    spec:
      containers:
      - name: analytics
        image: manrajbhullar/ga_analytics
        ports:
        - containerPort: 8100
        env:
        - name: DB_HOST1
          valueFrom: 
            configMapKeyRef:
              name: ga-entry-db
              key: DB_HOST
        - name: DB_HOST2
          valueFrom: 
            configMapKeyRef:
              name: ga-results-db
              key: DB_HOST
        resources:
          requests:
            cpu: 100m