apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ga-entry
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ga-entry
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5